__pycache__/utils.cpython-39.pyc
__pycache__/network.cpython-39.pyc
__pycache__/custom_dataset.cpython-39.pyc
error*
L1*
/BioInformedNN_old
/BioInformedNN
/DataDriven
/tb_logs
/classification_logs
/lightning_logs
/WB_classification_logs
./__pycache__/*
sparse_cca/*
*.npy
*.txt
*cpython*